## Operating System (VM environment) ##

# Rust needs at least Visual Studio 2013 Appveyor OS for MSVC targets.
os: Visual Studio 2015

## Build Matrix ##
# Multiple toolcahins are left to help detect bugs/regressions in nightly/
# beta rust.
environment:
  matrix:

### MSVC Toolchains ###

  # Stable 64-bit MSVC
    - channel: stable
      target: x86_64-pc-windows-msvc
  # Beta 64-bit MSVC
    - channel: beta
      target: x86_64-pc-windows-msvc
  # Nightly 64-bit MSVC
    - channel: nightly
      target: x86_64-pc-windows-msvc

### Allowed failures ###
# Ignore build failures on nightly/beta for CI checks
matrix:
  allow_failures:
    - channel: nightly
    - channel: beta

## Install Script ##

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV

## Build Script ##

# 'cargo test' takes care of building for us, so disable Appveyor's build stage. This prevents
# the "directory does not contain a project or solution file" error.
build: false

before_test:
- cargo build --release

test_script:
- cargo test --release --verbose %cargoflags%

## Artifacts ##
# Upload built files to AppVeyor cloud for deployment purposes
artifacts:
  - path: target/release/nano-vanity.exe
    name: ReleaseExe